# https://taskfile.dev

version: '3'

output: prefixed

vars:
  Name: yomo
  ExeName: yomo{{exeExt}}
  ExeDir: yomo 
  Version: 
    sh: git describe --always --tags --dirty
  Date:
    sh: git show -s --format=%cs {{.Commit}}
  Commit:
    sh: git rev-parse --short HEAD
  Module:
    sh: go list -m

tasks:
  default:
    cmds:
      - echo "{{.Name}}"
    silent: true

  build:
    desc: build yomo cli tools
    cmds:
      - echo "{{.Name}} building..."
      - go build -v -o {{.ExeDir}}/{{.ExeName}} -ldflags "-s -w -X {{.Module}}/cmd.Version={{.Version}} -X {{.Module}}/cmd.Date={{.Date}}" {{.ExeDir}}/main.go
      - echo "{{.Name}} built."
    generates:
      - "{{.ExeDir}}/{{.ExeName}}"
    sources:
      - "**/*.go"
    method: none
    silent: true

  run:
    desc: run yomo cli 
    deps: [build]
    cmds:
      - "{{.ExeDir}}/{{.ExeName}}"
    silent: false

  example:
    desc: example
    deps: [example-source,example-flow,example-sink]
    cmds:
      # - task: example-zipper
      # - task: example-source
      # - task: example-flow
      # - task: example-sink
      - echo "example"

  example-source:
    desc: run source application
    deps: [example-source-build]
    dir: "example/source"
    cmds:
      - "./source{{exeExt}}"
    silent: false

  example-source-build:
    desc: build source application
    dir: "example/source"
    cmds:
      - echo "source building..."
      - "go build -o source{{exeExt}} main.go"
      - echo "source built."
    silent: false

  example-flow:
    desc: "run flow function"
    deps: [build]
    cmds:
      - "{{.ExeDir}}/{{.ExeName}} run -n Noise example/flow/app.go"
    silent: false

  example-zipper:
    desc: "run zipper"
    deps: [build]
    cmds:
      - "{{.ExeDir}}/{{.ExeName}} serve -c example/zipper/workflow.yaml"
    silent: false

  example-sink:
    desc: run sink application
    deps: [example-sink-build]
    dir: "example/sink"
    cmds:
      - echo "source building..."
      - "./sink{{exeExt}}"
      - echo "sink built."
    silent: false

  example-sink-build:
    desc: build sink application
    dir: "example/sink"
    cmds:
      - "go build -o sink{{exeExt}} main.go"
    silent: false

  version:
    desc: "print version"
    cmds: 
      - echo "Version {{.Version}}({{.Date}})"
    silent: true
